In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[1,3]])

In [3]:
A

array([[2, 3],
       [1, 3]])

In [5]:
np.linalg.eig(A)

(array([0.69722436, 4.30277564]),
 array([[-0.91724574, -0.79325185],
        [ 0.3983218 , -0.60889368]]))

In [6]:
import scipy as sci

In [7]:
sci.linalg.eig(A)

(array([0.69722436+0.j, 4.30277564+0.j]),
 array([[-0.91724574, -0.79325185],
        [ 0.3983218 , -0.60889368]]))

In [8]:
B = np.array([[1,1],[0,2]])

In [9]:
B

array([[1, 1],
       [0, 2]])

In [10]:
A @ B

array([[2, 8],
       [1, 7]])

In [11]:
np.dot(A,B)

array([[2, 8],
       [1, 7]])

In [12]:
np.matmul(A,B)

array([[2, 8],
       [1, 7]])

In [13]:
np.linalg.det(A)

2.9999999999999996

In [14]:
np.linalg.det(B)

2.0

In [15]:
np.linalg.matrix_rank(A)

2

In [16]:
np.linalg.inv(A)

array([[ 1.        , -1.        ],
       [-0.33333333,  0.66666667]])